# Generated by Django 3.0.1 on 2019-12-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='level',
            field=models.CharField(choices=[('Hard', 'Hard'), ('Intermediate', 'Intermediate'), ('Easy', 'Easy')], default='Easy', help_text='Level of difficultly', max_length=15, verbose_name='Level'),
        ),
    ]
