# Generated by Django 2.2.5 on 2019-09-22 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_auto_20190922_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Quiz.Question')),
                ('answer_order', models.CharField(choices=[('content', 'Content'), ('random', 'Random')], help_text='The order in which the answer options are to be displayed', max_length=30, verbose_name='Answer Options Order')),
            ],
            options={
                'verbose_name': 'Multiple Choice Question',
            },
            bases=('Quiz.question',),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Enter the answer text to be displayed', max_length=1000, verbose_name='Answer text')),
                ('correct', models.BooleanField(default=False, help_text='Is this a correct Answer ?', verbose_name='Correct')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.MCQ', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
