# Generated by Django 2.2.5 on 2019-09-22 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_answer_mcq'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='single_correct',
            field=models.BooleanField(default=True, help_text='If selected, only one choice should have a correct answer', verbose_name='Single Correct'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.SubCategory', verbose_name='Sub-Category'),
        ),
    ]
