# Generated by Django 2.2.5 on 2019-09-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_auto_20190922_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='level',
            field=models.CharField(choices=[('Hard', 'Hard'), ('Intermediate', 'Intermediate'), ('Easy', 'Easy')], default='Easy', help_text='Level of difficultly', max_length=10, verbose_name='Level'),
        ),
    ]
