# Generated by Django 2.2.5 on 2019-09-23 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20190921_1153'),
        ('Quiz', '0006_quiz_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_on', models.DateTimeField(auto_now_add=True, verbose_name='Attempted Quiz on ')),
                ('Questions_attempted', models.PositiveSmallIntegerField(default=0, verbose_name='Question Attempted')),
                ('Questions_correct', models.PositiveSmallIntegerField(default=0, verbose_name='Questions Correctly answered')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Quiz', verbose_name='Quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Progress of Student',
            },
        ),
    ]
