# Generated by Django 2.2.5 on 2019-09-23 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.PositiveSmallIntegerField(default=1, help_text='Marks alloted to this question', validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Marks'),
        ),
    ]
