# Generated by Django 2.2.5 on 2019-09-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_auto_20190924_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='marks',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Marks Scored'),
        ),
    ]
