# Generated by Django 2.2.5 on 2019-09-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0010_progress_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
