# Generated by Django 2.2.5 on 2019-09-29 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='Comment')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('upvotes', models.IntegerField(default=0, verbose_name='Upvotes')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.Forum_answer', verbose_name='Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
