# Generated by Django 2.2.5 on 2019-09-29 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum_question',
            old_name='asked',
            new_name='asked_on',
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Asked on '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forum_answer',
            name='answered_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Answered on '),
            preserve_default=False,
        ),
    ]
