# Generated by Django 2.2.5 on 2019-10-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0003_auto_20190929_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='forum_question',
            name='topic',
            field=models.ManyToManyField(null=True, to='Forum.Topic', verbose_name='Topic'),
        ),
    ]
