# Generated by Django 2.2.5 on 2019-10-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0004_auto_20191001_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_question',
            name='topic',
            field=models.ManyToManyField(to='Forum.Topic', verbose_name='Topic'),
        ),
    ]
