# Generated by Django 2.2.5 on 2019-10-01 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0005_auto_20191001_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Question Author'),
        ),
    ]
