# Generated by Django 2.2.5 on 2019-09-13 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('year', models.CharField(choices=[('FE', 'First Year'), ('SE', 'Second Year'), ('TE', 'Third Year'), ('BE', 'Final Year')], default='FE', max_length=2)),
                ('div', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1)),
                ('branch', models.CharField(choices=[('Comps', 'Computers'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('Instru', 'Instru'), ('Mech', 'Mechanical')], default='Comps', max_length=10)),
                ('rollno', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
