# Generated by Django 3.0.1 on 2020-01-19 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='mate2_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mate 2 name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='mate3_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mate 3 name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='mate4_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mate 4 name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='problem2_selected',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ps2', to='Hackathon.problems', verbose_name='Selected problem statement 2'),
        ),
        migrations.AlterField(
            model_name='team',
            name='problem3_selected',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ps3', to='Hackathon.problems', verbose_name='Selected problem statement 3'),
        ),
        migrations.AlterField(
            model_name='team',
            name='solution2',
            field=models.CharField(blank=True, help_text='How will you solve it', max_length=500, verbose_name='Solution'),
        ),
        migrations.AlterField(
            model_name='team',
            name='solution3',
            field=models.CharField(blank=True, help_text='How will you solve it', max_length=500, verbose_name='Solution'),
        ),
    ]
