# Generated by Django 3.0.1 on 2020-01-20 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon', '0002_auto_20200119_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='mate2_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='team',
            name='mate2_name',
            field=models.CharField(max_length=50, verbose_name='Mate 2 name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='mate2_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,12}$')]),
        ),
        migrations.AlterField(
            model_name='team',
            name='size',
            field=models.PositiveSmallIntegerField(default=4, help_text='No. of player in a team', validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(2)], verbose_name='Team Size'),
        ),
    ]
