# Generated by Django 3.0.1 on 2020-01-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon', '0003_auto_20200120_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='college_name',
            field=models.CharField(default='RGIT', max_length=100, verbose_name='College Name'),
        ),
        migrations.AddField(
            model_name='team',
            name='leader_year',
            field=models.CharField(default='TE', max_length=20, verbose_name='Leader Current Year'),
        ),
        migrations.AddField(
            model_name='team',
            name='mate2_year',
            field=models.CharField(default='TE', max_length=20, verbose_name='Mate 2 Current Year'),
        ),
        migrations.AddField(
            model_name='team',
            name='mate3_year',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mate 3 Current Year'),
        ),
        migrations.AddField(
            model_name='team',
            name='mate4_year',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mate 4 Current Year'),
        ),
    ]
