# Generated by Django 3.0.1 on 2020-02-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon', '0005_auto_20200211_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='Category',
            field=models.CharField(choices=[('Machine Learning / Artificial Intelligence', 'Machine Learning / Artificial Intelligence'), ('Blockchain', 'Blockchain'), ('Web Development', 'Web Development'), ('Android Application', 'Android Application')], default='Machine Learning', max_length=50, verbose_name='Category'),
        ),
    ]
