# Generated by Django 3.0.1 on 2020-02-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon', '0006_auto_20200211_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='domain1',
            field=models.CharField(choices=[('Machine Learning / Artificial Intelligence', 'Machine Learning / Artificial Intelligence'), ('Blockchain', 'Blockchain'), ('Web Development', 'Web Development'), ('Android Application', 'Android Application')], max_length=50, verbose_name='Domain Preference 1'),
        ),
        migrations.AlterField(
            model_name='team',
            name='domain2',
            field=models.CharField(choices=[('Machine Learning / Artificial Intelligence', 'Machine Learning / Artificial Intelligence'), ('Blockchain', 'Blockchain'), ('Web Development', 'Web Development'), ('Android Application', 'Android Application')], max_length=50, verbose_name='Domain Preference 2'),
        ),
        migrations.AlterField(
            model_name='team',
            name='domain3',
            field=models.CharField(choices=[('Machine Learning / Artificial Intelligence', 'Machine Learning / Artificial Intelligence'), ('Blockchain', 'Blockchain'), ('Web Development', 'Web Development'), ('Android Application', 'Android Application')], max_length=50, verbose_name='Domain Preference 3'),
        ),
    ]
