# Generated by Django 3.0.1 on 2020-02-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon', '0007_auto_20200211_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='mate2_year',
            field=models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year')], default='TE', max_length=20, verbose_name='Mate 2 Current Year'),
        ),
        migrations.AlterField(
            model_name='team',
            name='mate3_year',
            field=models.CharField(blank=True, choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year')], max_length=20, verbose_name='Mate 3 Current Year'),
        ),
        migrations.AlterField(
            model_name='team',
            name='mate4_year',
            field=models.CharField(blank=True, choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year')], max_length=20, verbose_name='Mate 4 Current Year'),
        ),
    ]
