# Generated by Django 3.0.1 on 2020-02-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon', '0008_auto_20200211_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='leader_year',
            field=models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year')], default='TE', max_length=20, verbose_name='Leader Current Year'),
        ),
    ]
